version: '3.2'
services:
  ojs:
    build: .
    ports:
      - 8001:8000
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./files:/var/ojs_home/files
  ocs:
    build:
      context: .
      dockerfile: Dockerfile.ocs
    ports:
      - 8002:8000
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./files:/var/ocs_home/files
  db:
    image: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
